# Generated by Django 5.1.5 on 2025-03-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateusagelog',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
